CREATE TABLE `User_Role` (
RoleID TINYINT UNSIGNED NOT NULL,
Name VARCHAR(64) NOT NULL,
PRIMARY KEY(RoleID)
);

CREATE TABLE `User` (
UserID MEDIUMINT UNSIGNED,
Email VARCHAR(100) UNIQUE NOT NULL,
PasswordHash VARCHAR(100) NOT NULL,
RoleID TINYINT UNSIGNED NOT NULL, 
PRIMARY KEY (UserID),
FOREIGN KEY(RoleID) REFERENCES `User_Role`(RoleID)
);
